### ISSUE TITLE
sometimes players freeze in multiplayer

### ISSUE THREAD

**Issue by seiyria** [seiyria/Roguathia#47]
and by freeze I mean they just don't move. it's probably them being unable to navigate to a destination so their path disappears or something

**Comment by klusark** [comment]
I seem to be getting this quite often. I've only seen it happen so far when one of my players is dead (I just have two right now), although, it's probably unrelated.

**Comment by seiyria** [comment]
I've been getting handfuls of reports about this today. It didn't happen
much to me, but I suspect the ai is just giving up while trying to generate
a path to its target. However I'd it does that it's supposed to step
randomly, not sit still. Something else appears to be at play here.

**Comment by klusark** [comment]
I found the issue, although I'm not sure the best way to fix it. When a player descends, it calls ExploresDungeonBehavior.descend, which clears the target list, however, it only gets called on the player that triggers the decent, and not any of the other players, leaving the rest of the players with invalid target lists.

**Comment by seiyria** [comment]
I think the best solution is to call descend on all other players when they
descend.

**Comment by seiyria** [comment]
Not sure if that patch fixed it (so I won't close it just yet). I know that's what needed to be done, but I'll test it a bit more over the next few hours while I work on #45.

**Comment by seiyria** [comment]
I'm assuming this is closed now because the behavior seems to be fixed for me.
