### ISSUE TITLE
Unify independent dungeon crawlers into an actual adventuring party

### ISSUE THREAD

**Issue by brungre** [seiyria/Roguathia#5]
Basically, instead of each avatar acting on their own, they act together as a group for synergy and whatnot.  Human player would be able to determine marching order, with the first position being the "leader" of the party, and then the party would follow that leader single-file in the determined marching order (i.e., typical JRPG adventuring party snake).

---

Requirements/ideas: 

_(I would have used an ordered list but the markdown previewer is godsdamned stupid in that my 3rd main point would show up as a sub-item of the 2nd main point's bulleted item.  So lame)_
- Some interface option for determining marching order.  Ideally able to swap the configuration at any time to take advantage of actual human intervention (accidentally setting squishy glass cannon as party leader and walking into a meat grinder = bad & preventable).
- When combat occurs, the party splits back off of follow-mode to have their own classes' combat algorithms run. 
- Attacks from a narrow hallway have chance of hitting person(s) ahead of attacking party member.
  - Make it an accuracy/to-hit penalty, that can be eventually overcome by leveling up/magic gear/sheer dumb luck/etc.
  - Stack the to-hit penalty either additively or multiplicatively for each subsequent party member between attacking party member and their hostile target.  Perhaps 40% chance if one lunkhead is in front of the attacker, and each subsequent party member adds another 10% to the chance (additively).  Or if you want multiplicatively you could say the chance of hitting the intended target (X) is determined by the following calculation .6^(# of lunkheads between attacker and target)(initial chance of hitting intended target).
  - This intercept arrows calculation should also apply for any actor between the attacker and the target, and apply equally to the hostile attacks made against the adventuring party members. (It was a feature I loved in the old school Fallout games, where some hostile raider would go burst fire with his machine gun and totally riddle his fellow raider in the back by accident).
  - Maybe allow human player to decide what is an acceptable level of risk for ranged characters to attack through/past other party members.  Something like: _Base to-hit_ **75% -** _to-hit penalty from **2** lunkheads between attacker and target_ **50% >=** _player set threshold of_ **35%** returns **FALSE** so the attacking party member doesn't shoot an arrow into Lunkhead A's buttcheek.
  - AoE wizard spells can target through party members without incurring to-hit penalty (do they even have an accuracy rating/attack roll to begin with?  I can't remember in the last roguelike I played).  Was it that you target a square for the spell, and it had a X% chance to instead fall in one of the surrounding squares determined by a 1d8 roll?  
- Party members always know the location of the leader, and once the dust of combat & looting has settled resume the marching order.
  - Party members share loot, with the idea of giving the best equipment to the optimal party member for greater utility (no glass cannons wearing plate mail and meatslabs wearing a wizard robe). 

Cat tax
![supposed to be an ASCII cat](http://www.qqpr.com/ascii/img/ascii-1052.gif)

**Comment by seiyria** [comment]
I already told you I probably would not do this except make it possible to do via traits.

**Comment by brungre** [comment]
I was suggesting for initial release, but jotting down the note in case you do gain more developer support to work on it.

**Comment by seiyria** [comment]
With the way the game progressed, I don't see this as feasible anymore.
