### ISSUE TITLE
List of past player characters

### ISSUE THREAD

**Issue by Zireael07** [seiyria/Roguathia#51]
It would be nice if the player characters of the past would be written to a list. Especially the winners. So that I could see what race/class combination does the best or which ones are the most common for me.

**Comment by seiyria** [comment]
I'm definitely interested in doing this. I plan on having a more comprehensive history of characters when the graveyard is implemented, because some of them might come back to life as ghosts. The history itself would probably be relatively trivial, though, I'd just add a new tab under Log for it.

**Comment by Zireael07** [comment]
Just the history would be great, as the log scrolls down automatically. I think I had two winners, one yesterday and one today, but couldn't check anything on them as I wasn't looking at the game when they won :P
