### ISSUE TITLE
players sometimes seem to move more than once space per turn

### ISSUE THREAD

**Issue by klusark** [seiyria/Roguathia#58]
This may not actually be happening, but it looks like sometimes my players are moving more than one space per turn. I'm probably just seeing things, but I figured I'd create an issue in case any one else thought they were seeing things as well.

**Comment by seiyria** [comment]
It's definitely possible with the new AI that I missed something like this. I tried to terminate all movement paths with a single step, but it's possible I let them leak somehow. The easiest way to tell would be to slow the game down a lot and move down to one player so it's actually observable.

If you have many players, though, it's possible that the turn order is just messing with you - they get turns based on their speed and their speed can make them move twice at the rate another player moves once.

**Comment by klusark** [comment]
Hmm, ya, it's probably just the turn order then. I'll try slowing down the game though.

**Comment by seiyria** [comment]
I'm going to close this for now, as I'm inclined to believe it's speed doing this.
