### ISSUE TITLE
Spore race gets stuck orbiting loot

### ISSUE THREAD

**Issue by OneWingedDevil** [seiyria/Roguathia#65]
After killing some enemies, any adventurer playing the spore race seems to get stuck orbiting around the loot it can't pick up. I've noticed it with money on the ground, though it may also exhibit that behavior around other loot drops.

**Comment by seiyria** [comment]
Interesting, this racial bug should have been fixed a while ago.

**Comment by OneWingedDevil** [comment]
Nevermind on that, it was. Killed off my run so I could purchase the spore race and re-test it. It was fixed, though now I'm left wondering what the point of the spore race is, since I had assumed it wasn't supposed to be able to pick up anything as its gimmick. That's for the reddit thread, though.

**Comment by seiyria** [comment]
Originally the only races that could do things like that were humanoid (elf, gnome, etc). This caused a lot of confusion so all players get a few extra behaviors so everything logically makes sense.

The spore race is still used internally for spore monsters, though. All of the races you see there are used by monsters as well.
