### ISSUE TITLE
gauntlets should be twohanded

### ISSUE THREAD

**Issue by seiyria** [seiyria/Roguathia#68]
http://prntscr.com/9bf29s

Currently they're not, which creates silly situations.

**Comment by Ryan-Knowles** [comment]
Should this be applied to all hand slot items? Do we need 2 hand slots?

**Comment by seiyria** [comment]
No. Only items that are gauntlets. It's very easy to do - just annotate them with `@twoHanded`. It would theoretically be possible for there two be two separate bracelet items, for example, that only take one slot each. Gloves should be two slots (unless there is only a singular glove, that is).
