### ISSUE TITLE
Allow corpses stacking

### ISSUE THREAD

**Issue by swatjester** [seiyria/Roguathia#71]
Corpses make up 90% of your inventory, yet do nothing (yet). Even if they did do something, they still eat up a ton of screen real-estate in your inventory, making it difficult to get to actual equipment. 
Solution: Corpses of the same monster type (i.e. all "iguana" or all "chameleon") should be able to stack with each other instead of each displaying as a separate inventory line.  So instead of:

corpse of gecko
corpse of gecko
corpse of gecko
corpse of iguana

You get:

3 corpses of gecko
a corpse of iguana

I don't know if corpses can have blessed/cursed status, but potentially if that matters, they'd stack with corpses of like blessing status.

**Comment by seiyria** [comment]
Technically anything can have blessed/cursed. I definitely am interested in implementing item stacking, also. More-so, I'd be happy with a PR if you'd be willing to submit one!

**Comment by seiyria** [comment]
Turns out I already had item stacking implemented, it just needed some tuning.

**Comment by swatjester** [comment]
I wish I could help directly but I'm a producer, not an engineer.  I'm
happy to keep giving feedback if you'd like. Thanks for this project though!

On Friday, December 18, 2015, Kyle J. Kemp notifications@github.com wrote:

> Technically anything can have blessed/cursed. I definitely am interested
> in implementing item stacking, also. More-so, I'd be happy with a PR if
> you'd be willing to submit one!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/seiyria/Roguathia/issues/71#issuecomment-165943046.

## 

Sent from my iPad.

**Comment by seiyria** [comment]
Hey, no worries. Please do!
